name: lista_super
description: Lista de compras
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  equatable: ^2.0.8
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#0B0F1A"
  image: assets/splash.png

  android_12:
    image: assets/splash.png
    icon_background_color: "#0B0F1A"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/